export const DESIGN_ANGLES = [
  "Testimonial-Driven Landing Page",
  "Problem-Solution Story Page",
  "Urgency & Scarcity Funnel",
  "Educational Lead-In Page",
  "Comparison & Authority Page",
  "Video Sales Letter Page",
  "Quiz-Style Engagement Page",
  "Minimalist Direct-Offer Page",
  "Social Proof Wall Page",
  "Benefit-Stacking Long-Form Page",
];

export interface DFYPage {
  id: number;
  niche: string;
  pageName: string;
  designAngle: string;
  description: string;
  recommendedProducts: string[];
  headline: string;
  subheadline: string;
  bodyPoints: string[];
  ctaText: string;
}

export const NICHE_ACCENTS: Record<string, { primary: string; gradient: string; ring: string; badge: string }> = {
  "Health & Fitness": { primary: "#10b981", gradient: "from-emerald-500 to-teal-400", ring: "ring-emerald-500/30", badge: "bg-emerald-500/10 text-emerald-400 border-emerald-500/20" },
  "Personal Finance": { primary: "#06b6d4", gradient: "from-cyan-500 to-blue-400", ring: "ring-cyan-500/30", badge: "bg-cyan-500/10 text-cyan-400 border-cyan-500/20" },
  "Online Business": { primary: "#f59e0b", gradient: "from-amber-500 to-orange-400", ring: "ring-amber-500/30", badge: "bg-amber-500/10 text-amber-400 border-amber-500/20" },
  "Weight Loss": { primary: "#f43f5e", gradient: "from-rose-500 to-pink-400", ring: "ring-rose-500/30", badge: "bg-rose-500/10 text-rose-400 border-rose-500/20" },
  "Self-Improvement": { primary: "#a855f7", gradient: "from-purple-500 to-violet-400", ring: "ring-purple-500/30", badge: "bg-purple-500/10 text-purple-400 border-purple-500/20" },
};

export const DFY_PAGES: DFYPage[] = [
  // ─── Health & Fitness (10 pages) ───
  {
    id: 1, niche: "Health & Fitness", pageName: "FitLife Transformation", designAngle: DESIGN_ANGLES[0],
    description: "Testimonial-driven page featuring real transformation stories. Best for fitness programs and supplements.",
    recommendedProducts: ["Fitness programs", "Workout plans", "Health supplements", "Protein powders"],
    headline: "Real People. Real Transformations.",
    subheadline: "See how thousands changed their bodies — and their lives — with one simple system.",
    bodyPoints: ["Lost 30 lbs in 12 weeks — Sarah M.", "Gained lean muscle without the gym — James K.", "Finally feel confident at the beach — Priya T.", "Doctor said my bloodwork is perfect now — Robert L."],
    ctaText: "Start Your Transformation",
  },
  {
    id: 2, niche: "Health & Fitness", pageName: "30-Day Body Reset", designAngle: DESIGN_ANGLES[1],
    description: "Problem-solution narrative that addresses common health frustrations and presents your product as the fix.",
    recommendedProducts: ["Detox programs", "Meal plan subscriptions", "Fitness challenges", "Health coaching"],
    headline: "Tired of Feeling Tired?",
    subheadline: "You've tried every diet. Every workout plan. Nothing sticks. Here's why — and how to fix it in 30 days.",
    bodyPoints: ["The real reason diets fail (it's not willpower)", "How your metabolism is working against you", "The 30-day reset that changes everything", "No gym required — works from home"],
    ctaText: "Reset Your Body Now",
  },
  {
    id: 3, niche: "Health & Fitness", pageName: "Limited Spots Bootcamp", designAngle: DESIGN_ANGLES[2],
    description: "High-urgency page with countdown timer and limited spots messaging. Drives fast conversions.",
    recommendedProducts: ["Bootcamp programs", "Personal training", "Premium supplements", "Gym memberships"],
    headline: "Only 47 Spots Left This Month",
    subheadline: "Our elite fitness bootcamp fills up fast. Once spots are gone, enrollment closes until next quarter.",
    bodyPoints: ["12-week structured transformation program", "Personal coach assigned to you", "Members-only nutrition plan included", "97% completion rate — highest in the industry"],
    ctaText: "Claim Your Spot Before It's Gone",
  },
  {
    id: 4, niche: "Health & Fitness", pageName: "Health Science Hub", designAngle: DESIGN_ANGLES[3],
    description: "Educational lead-in that teaches a health concept then naturally recommends your product.",
    recommendedProducts: ["Nutrition guides", "Scientific supplements", "Health monitors", "Wellness apps"],
    headline: "The Science Behind Lasting Health",
    subheadline: "Harvard researchers just confirmed what ancient healers knew all along. Here's the breakthrough.",
    bodyPoints: ["New study reveals the #1 nutrient most people are missing", "Why 90% of supplements don't work (and what does)", "The cellular repair process your body needs activated", "How to measure your real health age in 60 seconds"],
    ctaText: "Discover the Science",
  },
  {
    id: 5, niche: "Health & Fitness", pageName: "Product Showdown", designAngle: DESIGN_ANGLES[4],
    description: "Comparison page that positions your recommended product against alternatives. Builds authority.",
    recommendedProducts: ["Any health product with competitors", "Premium supplements", "Fitness equipment", "Health plans"],
    headline: "We Tested 50 Health Products So You Don't Have To",
    subheadline: "Independent lab results. No sponsorships. Just the truth about what actually works.",
    bodyPoints: ["Side-by-side ingredient analysis", "Third-party lab verified results", "Cost per serving breakdown", "Our #1 pick surprised even us"],
    ctaText: "See the Winner",
  },
  {
    id: 6, niche: "Health & Fitness", pageName: "Trainer Video Pitch", designAngle: DESIGN_ANGLES[5],
    description: "Video-first page with an embedded sales video. Minimal text, maximum impact.",
    recommendedProducts: ["Video workout programs", "Online coaching", "Fitness courses", "Health masterclasses"],
    headline: "Watch This Before Your Next Workout",
    subheadline: "In the next 7 minutes, you'll learn the #1 training mistake keeping you from results.",
    bodyPoints: ["Why more exercise isn't the answer", "The 20-minute method that outperforms 2-hour gym sessions", "Used by Olympic trainers worldwide", "See the results in your first week"],
    ctaText: "Watch the Free Training",
  },
  {
    id: 7, niche: "Health & Fitness", pageName: "What's Your Fitness Type?", designAngle: DESIGN_ANGLES[6],
    description: "Interactive quiz that segments visitors then recommends the perfect product based on their answers.",
    recommendedProducts: ["Personalized fitness plans", "Custom supplements", "Tailored meal plans", "Health assessments"],
    headline: "What's Your Body Type?",
    subheadline: "Take this 60-second quiz to discover your metabolic profile and get a plan built for YOUR body.",
    bodyPoints: ["Ectomorph, Mesomorph, or Endomorph — each needs a different approach", "Your metabolism speed determines your ideal diet", "Wrong exercise for your type = wasted effort", "Get your personalized blueprint instantly"],
    ctaText: "Take the Quiz",
  },
  {
    id: 8, niche: "Health & Fitness", pageName: "Clean & Direct Offer", designAngle: DESIGN_ANGLES[7],
    description: "Minimalist page — product image, 3 bullet points, CTA. No distractions. Pure conversion.",
    recommendedProducts: ["Simple supplements", "Single product offers", "Ebooks", "Quick-start guides"],
    headline: "One Supplement. Total Health.",
    subheadline: "Everything your body needs in a single daily scoop.",
    bodyPoints: ["23 essential vitamins & minerals", "Clinically dosed ingredients", "30-day money back guarantee"],
    ctaText: "Get Yours Now",
  },
  {
    id: 9, niche: "Health & Fitness", pageName: "Community Results Wall", designAngle: DESIGN_ANGLES[8],
    description: "Wall of social proof — screenshots, testimonials, before/after photos. Builds massive trust.",
    recommendedProducts: ["Transformation programs", "Weight loss products", "Fitness communities", "Coaching programs"],
    headline: "10,000+ Success Stories and Counting",
    subheadline: "Don't take our word for it. Here's what our community has to say.",
    bodyPoints: ["\"Best decision I ever made\" — ★★★★★", "\"Results in the first week\" — ★★★★★", "\"My doctor was shocked\" — ★★★★★", "\"I finally feel like myself again\" — ★★★★★", "\"Wish I started sooner\" — ★★★★★", "\"Changed my whole family's life\" — ★★★★★"],
    ctaText: "Join the Community",
  },
  {
    id: 10, niche: "Health & Fitness", pageName: "Ultimate Health Stack", designAngle: DESIGN_ANGLES[9],
    description: "Long-form page that stacks benefit after benefit with detailed explanations and proof points.",
    recommendedProducts: ["High-ticket health programs", "Comprehensive wellness bundles", "Premium coaching", "Subscription products"],
    headline: "The Complete Health System That Does It All",
    subheadline: "Nutrition. Exercise. Sleep. Stress. Mental clarity. One system covers everything.",
    bodyPoints: ["Custom meal plans generated weekly by AI", "Adaptive workout programming that evolves with you", "Sleep optimization protocol included", "Stress management & meditation library", "Monthly 1-on-1 coaching call", "Private community of 50,000+ members", "Supplement guide with exact brands & doses", "Progress tracking dashboard"],
    ctaText: "Get the Complete System",
  },

  // ─── Personal Finance (10 pages) ───
  {
    id: 11, niche: "Personal Finance", pageName: "Wealth Builder Stories", designAngle: DESIGN_ANGLES[0],
    description: "Real success stories of people who built wealth using the recommended system. Trust-focused.",
    recommendedProducts: ["Investment courses", "Financial planning tools", "Budgeting apps", "Trading programs"],
    headline: "From Paycheck-to-Paycheck to Financial Freedom",
    subheadline: "Meet the everyday people who built real wealth — starting from zero.",
    bodyPoints: ["\"Paid off $47K in debt in 18 months\" — Michael R.", "\"Built a $200K portfolio starting with $50/month\" — Lisa T.", "\"Retired 15 years early\" — David & Karen W.", "\"Went from negative net worth to six figures\" — Amanda J."],
    ctaText: "Start Building Wealth",
  },
  {
    id: 12, niche: "Personal Finance", pageName: "Debt to Freedom", designAngle: DESIGN_ANGLES[1],
    description: "Story-driven page about escaping debt and building wealth. Emotionally compelling.",
    recommendedProducts: ["Debt management programs", "Credit repair tools", "Financial literacy courses", "Savings systems"],
    headline: "I Was $89,000 in Debt. Here's How I Got Out.",
    subheadline: "The system banks don't want you to know about. No gimmicks. No bankruptcy. Just math and discipline.",
    bodyPoints: ["Why minimum payments are designed to keep you broke", "The debt avalanche method that actually works", "How to negotiate lower interest rates (script included)", "The psychological trick that makes saving automatic"],
    ctaText: "Get the Debt Freedom Plan",
  },
  {
    id: 13, niche: "Personal Finance", pageName: "Flash Investment Deal", designAngle: DESIGN_ANGLES[2],
    description: "Limited-time offer page for investment/trading products. Creates urgency to act now.",
    recommendedProducts: ["Trading signals", "Investment newsletters", "Stock picks services", "Crypto courses"],
    headline: "This Offer Expires at Midnight",
    subheadline: "Get lifetime access to our premium investment signals at 70% off. 127 spots remaining.",
    bodyPoints: ["Average 23% annual returns for members", "Daily alerts sent to your phone", "Works for stocks, crypto, and forex", "Cancel anytime — but you won't want to"],
    ctaText: "Lock In Your Discount",
  },
  {
    id: 14, niche: "Personal Finance", pageName: "Money IQ Academy", designAngle: DESIGN_ANGLES[3],
    description: "Educational page that teaches a financial concept then leads to product recommendation.",
    recommendedProducts: ["Financial education courses", "Investment guides", "Tax optimization tools", "Wealth building ebooks"],
    headline: "The Wealth Formula They Don't Teach in School",
    subheadline: "Understanding these 3 principles separates the wealthy from everyone else.",
    bodyPoints: ["Compound interest: the 8th wonder of the world", "Tax-advantaged accounts most people ignore", "The 50/30/20 rule (and why you should break it)", "How the wealthy invest differently than the middle class"],
    ctaText: "Unlock the Full Course",
  },
  {
    id: 15, niche: "Personal Finance", pageName: "Tool Comparison Matrix", designAngle: DESIGN_ANGLES[4],
    description: "Side-by-side comparison of financial tools, positioning your recommended product as the winner.",
    recommendedProducts: ["Budgeting apps", "Investment platforms", "Financial software", "Banking products"],
    headline: "We Analyzed Every Financial Tool on the Market",
    subheadline: "37 tools tested across 12 criteria. Here are the definitive results.",
    bodyPoints: ["Fees comparison (hidden charges exposed)", "Feature-by-feature breakdown", "Real user satisfaction scores", "Our #1 recommendation for 2025"],
    ctaText: "See the Full Comparison",
  },
  {
    id: 16, niche: "Personal Finance", pageName: "Millionaire Mindset Video", designAngle: DESIGN_ANGLES[5],
    description: "Video sales letter focused on the wealth mindset shift. Powerful for high-ticket offers.",
    recommendedProducts: ["High-ticket mentorship", "Wealth coaching", "Premium investment courses", "Mastermind groups"],
    headline: "The 11-Minute Video That Changed How I Think About Money",
    subheadline: "A self-made millionaire reveals the mental shift that made everything click.",
    bodyPoints: ["Why saving alone will never make you rich", "The asset mindset vs. the expense mindset", "How to spot income opportunities everywhere", "The one habit all millionaires share"],
    ctaText: "Watch the Video Now",
  },
  {
    id: 17, niche: "Personal Finance", pageName: "Financial Freedom Quiz", designAngle: DESIGN_ANGLES[6],
    description: "Quiz that assesses financial health and recommends the perfect starting product.",
    recommendedProducts: ["Personalized financial plans", "Budgeting systems", "Investment starter kits", "Financial assessments"],
    headline: "What's Your Financial Freedom Score?",
    subheadline: "Answer 8 quick questions and discover exactly where you stand — and what to do next.",
    bodyPoints: ["Personalized score from 0 to 100", "Custom action plan based on your situation", "Identify your biggest money leak", "Get matched with the right tools for your level"],
    ctaText: "Calculate My Score",
  },
  {
    id: 18, niche: "Personal Finance", pageName: "One-Click Wealth Tool", designAngle: DESIGN_ANGLES[7],
    description: "Clean, simple page for a single financial product. No fluff, just the offer.",
    recommendedProducts: ["Single financial tools", "Ebooks", "Quick-start investment guides", "Budget templates"],
    headline: "Automate Your Finances in 15 Minutes.",
    subheadline: "One tool. Set it up once. Watch your wealth grow.",
    bodyPoints: ["Auto-invests your spare change", "AI-optimized portfolio allocation", "Bank-level 256-bit encryption"],
    ctaText: "Start for Free",
  },
  {
    id: 19, niche: "Personal Finance", pageName: "Investor Success Board", designAngle: DESIGN_ANGLES[8],
    description: "Wall of investor testimonials and earnings screenshots. Builds confidence to buy.",
    recommendedProducts: ["Trading programs", "Investment communities", "Signal services", "Portfolio tools"],
    headline: "Our Members' Results Speak for Themselves",
    subheadline: "Verified earnings. Real portfolios. No cherry-picked screenshots.",
    bodyPoints: ["+$12,400 in 3 months — verified by bank statement", "+$8,750 first month — complete beginner", "+$34,200 this year — part-time investor", "+$5,100 in week one — following signals only", "Portfolio up 47% YTD — using the exact strategy", "$0 to $100K portfolio in 14 months — documented journey"],
    ctaText: "Join the Winners",
  },
  {
    id: 20, niche: "Personal Finance", pageName: "Complete Money System", designAngle: DESIGN_ANGLES[9],
    description: "Comprehensive long-form page covering every financial benefit and feature in detail.",
    recommendedProducts: ["All-in-one financial systems", "Comprehensive wealth courses", "Premium financial coaching", "Bundle offers"],
    headline: "The All-In-One Money Management System",
    subheadline: "Budgeting. Investing. Tax optimization. Debt payoff. Retirement planning. All in one place.",
    bodyPoints: ["AI-powered budget that learns your habits", "Automated investment portfolio management", "Tax-loss harvesting saves you thousands yearly", "Debt payoff accelerator with custom timeline", "Retirement calculator with Monte Carlo simulations", "Weekly market analysis newsletter", "Live Q&A with certified financial planners", "Private Slack community with 15,000+ members"],
    ctaText: "Get the Complete System",
  },

  // ─── Online Business (10 pages) ───
  {
    id: 21, niche: "Online Business", pageName: "Entrepreneur Success Stories", designAngle: DESIGN_ANGLES[0],
    description: "Feature real entrepreneur journeys from zero to profit. Inspires action.",
    recommendedProducts: ["Business courses", "Coaching programs", "SaaS tools", "Marketing systems"],
    headline: "They Started With Nothing. Now They're Free.",
    subheadline: "Real stories from real entrepreneurs who built profitable online businesses from scratch.",
    bodyPoints: ["\"From barista to $15K/month in 6 months\" — Chris P.", "\"Quit my corporate job after month 3\" — Nina S.", "\"Built a 6-figure agency while still employed\" — Marco D.", "\"Single mom making $8K/month from home\" — Tasha R."],
    ctaText: "Start Your Journey",
  },
  {
    id: 22, niche: "Online Business", pageName: "Escape the 9-to-5", designAngle: DESIGN_ANGLES[1],
    description: "Problem-solution narrative about leaving corporate life for online freedom.",
    recommendedProducts: ["Side hustle programs", "Freelance courses", "Digital product guides", "Online business blueprints"],
    headline: "Your Boss Doesn't Determine Your Worth. You Do.",
    subheadline: "The corporate ladder is broken. Here's the bridge to building something that's truly yours.",
    bodyPoints: ["Why promotions and raises will never make you rich", "The side-income model that replaces your salary in 90 days", "How to build while employed (without burning out)", "The exact first 3 steps to take this week"],
    ctaText: "Escape the 9-to-5",
  },
  {
    id: 23, niche: "Online Business", pageName: "Launch Special Access", designAngle: DESIGN_ANGLES[2],
    description: "Limited seats / early access page. Creates FOMO for business products.",
    recommendedProducts: ["Course launches", "Mastermind groups", "Software beta access", "Exclusive training"],
    headline: "Early Access: Closes in 48 Hours",
    subheadline: "Be one of the first 200 to access the system that's already generating $2.3M for beta users.",
    bodyPoints: ["Beta members averaging $4,700/month", "Founding member pricing — never available again", "Includes lifetime updates and support", "Only 61 spots remaining as of today"],
    ctaText: "Get Early Access Now",
  },
  {
    id: 24, niche: "Online Business", pageName: "Business Blueprint Class", designAngle: DESIGN_ANGLES[3],
    description: "Free value educational page that teaches a business strategy, then upsells the full system.",
    recommendedProducts: ["Full business systems", "Advanced courses", "Coaching programs", "Marketing tools"],
    headline: "Free Masterclass: The 3-Step Online Business Blueprint",
    subheadline: "Learn the exact framework used by 10,000+ successful online entrepreneurs.",
    bodyPoints: ["Step 1: Find your profitable niche (the data-driven way)", "Step 2: Build your automated sales funnel", "Step 3: Scale with paid traffic and partnerships", "Bonus: The tool stack that runs a $10K/month business"],
    ctaText: "Watch the Free Masterclass",
  },
  {
    id: 25, niche: "Online Business", pageName: "Platform Face-Off", designAngle: DESIGN_ANGLES[4],
    description: "Compare business tools/platforms and recommend the best option with your affiliate link.",
    recommendedProducts: ["Website builders", "Email platforms", "CRM tools", "Marketing software"],
    headline: "Shopify vs. WordPress vs. ClickFunnels: The Definitive Comparison",
    subheadline: "We spent 200+ hours testing every major platform. Here's the honest truth.",
    bodyPoints: ["Pricing breakdown (including hidden fees)", "Ease of use rating for beginners", "Scalability for 6-figure businesses", "Our recommendation for each business type"],
    ctaText: "See the Winner",
  },
  {
    id: 26, niche: "Online Business", pageName: "CEO Video Walkthrough", designAngle: DESIGN_ANGLES[5],
    description: "Video-first page where the product creator walks through the business system.",
    recommendedProducts: ["Video courses", "Software demos", "Business training", "Webinar replays"],
    headline: "Watch Me Build a $5K/Month Business in Real Time",
    subheadline: "No theory. No fluff. Just a screen recording of the exact process — start to finish.",
    bodyPoints: ["Full walkthrough of the business setup", "See every click, every tool, every decision", "Includes the exact templates and scripts used", "Follow along and build yours simultaneously"],
    ctaText: "Watch the Walkthrough",
  },
  {
    id: 27, niche: "Online Business", pageName: "What Business Fits You?", designAngle: DESIGN_ANGLES[6],
    description: "Interactive quiz to find the right online business model, then recommends matching products.",
    recommendedProducts: ["Niche-specific courses", "Business model guides", "Personalized coaching", "Starter kits"],
    headline: "Which Online Business Model Is Right for You?",
    subheadline: "Answer 5 questions and we'll match you with the perfect business model for your skills and goals.",
    bodyPoints: ["E-commerce, affiliate marketing, SaaS, or services?", "Factors: time available, budget, skills, goals", "Each model has a different path to $10K/month", "Get your personalized roadmap instantly"],
    ctaText: "Find My Perfect Business",
  },
  {
    id: 28, niche: "Online Business", pageName: "Quick-Start Business Kit", designAngle: DESIGN_ANGLES[7],
    description: "Minimalist direct-offer page for a business starter kit or tool. Fast conversions.",
    recommendedProducts: ["Starter kits", "Templates", "Business ebooks", "Quick-launch tools"],
    headline: "Launch Your Business This Weekend.",
    subheadline: "Everything you need in one kit. Templates. Scripts. Tools. Go.",
    bodyPoints: ["50+ proven email templates", "Complete funnel blueprints", "Plug-and-play ad creatives"],
    ctaText: "Get the Starter Kit",
  },
  {
    id: 29, niche: "Online Business", pageName: "Revenue Screenshot Wall", designAngle: DESIGN_ANGLES[8],
    description: "Social proof page with revenue screenshots, customer wins, and community highlights.",
    recommendedProducts: ["Income-generating systems", "Affiliate programs", "Business communities", "Revenue tools"],
    headline: "Real Revenue. Real People. Real Proof.",
    subheadline: "Unedited screenshots from our community dashboard. Updated daily.",
    bodyPoints: ["$11,340 this month — Day 47 using the system", "$6,200 recurring — fully automated", "$22,500 last quarter — starting from zero", "$3,800 in first 2 weeks — complete beginner", "$45,000 total earned — 8 months in", "$8,900 passive — works while I sleep"],
    ctaText: "See How They Did It",
  },
  {
    id: 30, niche: "Online Business", pageName: "Empire Builder System", designAngle: DESIGN_ANGLES[9],
    description: "Long-form page detailing every feature, benefit, and bonus of a comprehensive business system.",
    recommendedProducts: ["All-in-one business systems", "Premium courses", "High-ticket coaching", "Enterprise tools"],
    headline: "The Complete Online Business Operating System",
    subheadline: "Website. Funnels. Email. Ads. Analytics. Support. Automation. All built in.",
    bodyPoints: ["Drag-and-drop website builder with 200+ templates", "Built-in email marketing with AI copywriting", "Sales funnel builder with A/B testing", "Payment processing with 0% platform fees", "Customer support helpdesk included", "Advanced analytics and conversion tracking", "Affiliate program manager built-in", "24/7 live chat support from real humans"],
    ctaText: "Get the Complete System",
  },

  // ─── Weight Loss (10 pages) ───
  {
    id: 31, niche: "Weight Loss", pageName: "Real Transformations", designAngle: DESIGN_ANGLES[0],
    description: "Before/after transformation stories that prove the product works. Highly persuasive.",
    recommendedProducts: ["Weight loss programs", "Diet plans", "Supplements", "Fitness apps"],
    headline: "These Transformations Are 100% Real",
    subheadline: "Verified results from real people. No photoshop. No paid actors. Just the truth.",
    bodyPoints: ["\"Down 45 lbs — I feel 20 years younger\" — Karen, 52", "\"Lost 30 lbs without giving up carbs\" — Mike, 34", "\"Finally fit in my wedding dress\" — Jessica, 28", "\"My energy is through the roof\" — Tom, 41"],
    ctaText: "See More Transformations",
  },
  {
    id: 32, niche: "Weight Loss", pageName: "My Weight Loss Journey", designAngle: DESIGN_ANGLES[1],
    description: "Personal story page about struggling with weight and finding the solution.",
    recommendedProducts: ["Diet programs", "Meal plans", "Exercise guides", "Weight loss supplements"],
    headline: "I Tried Everything. Then I Found This.",
    subheadline: "After 10 years of yo-yo dieting, I finally discovered what actually works — and it's not what you think.",
    bodyPoints: ["Why willpower-based diets always fail", "The hormonal imbalance nobody talks about", "The simple switch that changed everything", "How I lost 50 lbs without starving myself"],
    ctaText: "Read My Full Story",
  },
  {
    id: 33, niche: "Weight Loss", pageName: "Summer Body Countdown", designAngle: DESIGN_ANGLES[2],
    description: "Seasonal urgency page with countdown. Perfect for time-sensitive weight loss offers.",
    recommendedProducts: ["Fast-result programs", "30-day challenges", "Detox kits", "Quick-start diets"],
    headline: "12 Weeks Until Summer. Your Countdown Starts Now.",
    subheadline: "Join the challenge that's helped 50,000+ people get beach-ready. Enrollment closes Friday.",
    bodyPoints: ["Structured 12-week transformation program", "Daily meal plans with grocery lists", "Quick home workouts (20 min or less)", "Average member loses 20-35 lbs"],
    ctaText: "Join the Challenge",
  },
  {
    id: 34, niche: "Weight Loss", pageName: "Science of Fat Loss", designAngle: DESIGN_ANGLES[3],
    description: "Educational page explaining the science behind weight loss, then recommending the product.",
    recommendedProducts: ["Science-backed supplements", "Metabolic programs", "Nutrition courses", "Health monitoring tools"],
    headline: "Why 95% of Diets Fail (According to Science)",
    subheadline: "New research from Stanford reveals the metabolic switch that determines whether you lose weight or gain it back.",
    bodyPoints: ["The leptin resistance problem explained simply", "Why eating less can actually make you gain weight", "The metabolic reset protocol backed by 14 studies", "How to activate your body's natural fat-burning mode"],
    ctaText: "Learn the Science",
  },
  {
    id: 35, niche: "Weight Loss", pageName: "Diet Plan Showdown", designAngle: DESIGN_ANGLES[4],
    description: "Compares popular diets and recommends your product as the best approach.",
    recommendedProducts: ["Diet comparison guides", "Flexible diet programs", "Nutrition plans", "Custom meal services"],
    headline: "Keto vs. Intermittent Fasting vs. Mediterranean: Which Actually Works?",
    subheadline: "We analyzed 5 years of data across 12,000 users. The results are surprising.",
    bodyPoints: ["Head-to-head weight loss results after 6 months", "Sustainability score — which diet people actually stick to", "Nutritional completeness comparison", "The hybrid approach that beats them all"],
    ctaText: "See the Full Results",
  },
  {
    id: 36, niche: "Weight Loss", pageName: "Coach's Video Message", designAngle: DESIGN_ANGLES[5],
    description: "Video-led page from a coach/trainer explaining the weight loss method.",
    recommendedProducts: ["Video fitness programs", "Online coaching", "Training courses", "Workout subscriptions"],
    headline: "Your Coach Has a Message for You",
    subheadline: "In 9 minutes, you'll understand why everything you've been told about weight loss is wrong.",
    bodyPoints: ["The #1 mistake that keeps people overweight", "Why exercise alone won't get you there", "The nutrition framework that makes it effortless", "Your custom plan starts immediately after watching"],
    ctaText: "Watch the Video",
  },
  {
    id: 37, niche: "Weight Loss", pageName: "Find Your Diet Match", designAngle: DESIGN_ANGLES[6],
    description: "Quiz that identifies the visitor's body type and recommends the ideal weight loss product.",
    recommendedProducts: ["Personalized diet plans", "Body-type programs", "Custom supplements", "Metabolism assessments"],
    headline: "What's the Best Diet for YOUR Body Type?",
    subheadline: "Your genetics determine which foods make you gain or lose weight. Take this quiz to find out.",
    bodyPoints: ["Discover your metabolic type in 90 seconds", "Get a diet plan matched to your biology", "Learn which exercises burn fat fastest for you", "Personalized supplement recommendations included"],
    ctaText: "Take the Body Type Quiz",
  },
  {
    id: 38, niche: "Weight Loss", pageName: "One Simple Solution", designAngle: DESIGN_ANGLES[7],
    description: "Ultra-clean page with one product, one message, one CTA. Highest conversion potential.",
    recommendedProducts: ["Single supplements", "Detox products", "Simple diet guides", "Quick-fix programs"],
    headline: "One Scoop. Every Morning. That's It.",
    subheadline: "The simplest weight loss solution that actually delivers results.",
    bodyPoints: ["Clinically proven ingredients", "Suppresses cravings naturally", "Boosts metabolism by up to 30%"],
    ctaText: "Try It Risk-Free",
  },
  {
    id: 39, niche: "Weight Loss", pageName: "Community Wins Gallery", designAngle: DESIGN_ANGLES[8],
    description: "Gallery of community success stories, weight loss photos, and celebration posts.",
    recommendedProducts: ["Community-based programs", "Challenge groups", "Accountability systems", "Social diet apps"],
    headline: "The Results Wall: 50,000+ Transformations",
    subheadline: "Every week, hundreds of new success stories pour in. Here are this month's highlights.",
    bodyPoints: ["-35 lbs in 90 days — ★★★★★ Verified", "-22 lbs, off all medications — ★★★★★ Verified", "-50 lbs, ran first 5K — ★★★★★ Verified", "-18 lbs in 6 weeks, effortless — ★★★★★ Verified", "-40 lbs, best shape of my life at 55 — ★★★★★ Verified", "-28 lbs, more energy than my 20s — ★★★★★ Verified"],
    ctaText: "Join the Community",
  },
  {
    id: 40, niche: "Weight Loss", pageName: "Total Body Overhaul", designAngle: DESIGN_ANGLES[9],
    description: "Comprehensive long-form page covering nutrition, exercise, mindset, and supplements.",
    recommendedProducts: ["Complete weight loss systems", "Bundle offers", "Premium coaching", "Subscription programs"],
    headline: "The Total Body Overhaul: Everything You Need to Transform",
    subheadline: "Nutrition. Exercise. Mindset. Supplements. Sleep. Stress. Every angle covered.",
    bodyPoints: ["Personalized meal plans updated weekly", "Home & gym workout options (15-45 min)", "Mindset coaching to break emotional eating", "Supplement protocol for accelerated results", "Sleep optimization for better metabolism", "Stress management to lower cortisol", "Weekly check-ins with your coach", "Private community for accountability"],
    ctaText: "Start the Overhaul",
  },

  // ─── Self-Improvement (10 pages) ───
  {
    id: 41, niche: "Self-Improvement", pageName: "Growth Journeys", designAngle: DESIGN_ANGLES[0],
    description: "Stories of personal transformation — from stuck to thriving. Powerful social proof.",
    recommendedProducts: ["Personal development courses", "Coaching programs", "Mindset books", "Habit-building tools"],
    headline: "They Were Stuck. Then Everything Changed.",
    subheadline: "Real stories of personal breakthroughs that will inspire your own transformation.",
    bodyPoints: ["\"Went from depressed to running a business I love\" — Alex K.", "\"Overcame social anxiety and built a network\" — Samira B.", "\"Doubled my income by changing my mindset\" — Jordan M.", "\"Found my purpose at 45 — it's never too late\" — Patricia N."],
    ctaText: "Start Your Growth Journey",
  },
  {
    id: 42, niche: "Self-Improvement", pageName: "Break Free From Limits", designAngle: DESIGN_ANGLES[1],
    description: "Problem-solution page addressing limiting beliefs, procrastination, and self-sabotage.",
    recommendedProducts: ["Mindset programs", "Therapy tools", "Self-help courses", "Personal coaching"],
    headline: "The Invisible Wall Between You and Your Best Life",
    subheadline: "Limiting beliefs are running your life on autopilot. Here's how to take back control.",
    bodyPoints: ["The 3 beliefs secretly holding you back", "Why positive thinking alone doesn't work", "The neuroscience of rewiring your brain", "A 21-day protocol that creates permanent change"],
    ctaText: "Break Free Today",
  },
  {
    id: 43, niche: "Self-Improvement", pageName: "Last Chance Enrollment", designAngle: DESIGN_ANGLES[2],
    description: "Urgency-driven page for limited enrollment programs. Creates immediate action.",
    recommendedProducts: ["Cohort-based courses", "Live workshops", "Mentorship programs", "Exclusive events"],
    headline: "Final Call: Enrollment Closes Tonight",
    subheadline: "The next cohort of the Life Mastery Program starts Monday. Only 23 seats remain.",
    bodyPoints: ["8-week live group coaching program", "Direct access to world-class mentors", "Cohort-based — you grow with your peers", "Alumni network of 5,000+ high achievers"],
    ctaText: "Enroll Before Midnight",
  },
  {
    id: 44, niche: "Self-Improvement", pageName: "Success Mindset Lesson", designAngle: DESIGN_ANGLES[3],
    description: "Teaches a powerful mindset concept, then recommends the full program to go deeper.",
    recommendedProducts: ["Full development programs", "Advanced courses", "Coaching subscriptions", "Learning platforms"],
    headline: "The One Mental Model That Changes Everything",
    subheadline: "Used by CEOs, athletes, and peak performers. Once you see it, you can't unsee it.",
    bodyPoints: ["Why most self-improvement advice keeps you stuck", "The identity-first approach to lasting change", "How to make discipline automatic (not forced)", "The compound effect of small daily decisions"],
    ctaText: "Learn the Mental Model",
  },
  {
    id: 45, niche: "Self-Improvement", pageName: "Method Comparison Guide", designAngle: DESIGN_ANGLES[4],
    description: "Compares self-improvement methods and frameworks, recommending the best one.",
    recommendedProducts: ["Framework-based programs", "System courses", "Methodology guides", "Structured plans"],
    headline: "Atomic Habits vs. 75 Hard vs. Miracle Morning: What Actually Works?",
    subheadline: "We surveyed 5,000 people who tried the most popular self-improvement methods. Here's the data.",
    bodyPoints: ["Completion rates for each method", "Long-term results after 12 months", "Which personality types suit which method", "The combined approach that outperforms them all"],
    ctaText: "See the Comparison",
  },
  {
    id: 46, niche: "Self-Improvement", pageName: "Keynote Video Page", designAngle: DESIGN_ANGLES[5],
    description: "Inspirational video page with a keynote-style presentation about personal growth.",
    recommendedProducts: ["Video courses", "Masterclass subscriptions", "TED-style programs", "Motivation memberships"],
    headline: "This Talk Will Change How You See Yourself",
    subheadline: "15 minutes. One perspective shift. A lifetime of impact.",
    bodyPoints: ["Why your self-image controls your results", "The mirror exercise used by Navy SEALs", "How to reprogram your internal dialogue", "The audience gave this a 5-minute standing ovation"],
    ctaText: "Watch the Keynote",
  },
  {
    id: 47, niche: "Self-Improvement", pageName: "Discover Your Strengths", designAngle: DESIGN_ANGLES[6],
    description: "Personality/strengths quiz that leads to a tailored product recommendation.",
    recommendedProducts: ["Personality assessments", "Strengths programs", "Custom coaching", "Personalized plans"],
    headline: "What's Your Hidden Superpower?",
    subheadline: "This assessment reveals the unique strengths you're not leveraging — and shows you how to use them.",
    bodyPoints: ["Backed by positive psychology research", "Identifies your top 5 character strengths", "Shows how to apply them in career and relationships", "Includes a personalized development roadmap"],
    ctaText: "Discover My Strengths",
  },
  {
    id: 48, niche: "Self-Improvement", pageName: "Simple Daily System", designAngle: DESIGN_ANGLES[7],
    description: "Clean minimalist page for a daily habit or routine product. Simple and effective.",
    recommendedProducts: ["Daily planners", "Habit apps", "Journaling tools", "Morning routine guides"],
    headline: "5 Minutes. Every Morning. Life Changed.",
    subheadline: "The simplest daily practice with the biggest impact on your life.",
    bodyPoints: ["Guided morning journaling", "Science-backed gratitude protocol", "Takes less time than making coffee"],
    ctaText: "Start Tomorrow Morning",
  },
  {
    id: 49, niche: "Self-Improvement", pageName: "Student Wins Showcase", designAngle: DESIGN_ANGLES[8],
    description: "Showcase of student success stories, reviews, and achievement highlights.",
    recommendedProducts: ["Proven courses", "Community programs", "Mentorship systems", "Student-driven platforms"],
    headline: "What Our Students Are Achieving",
    subheadline: "These results aren't exceptional — they're the standard in our community.",
    bodyPoints: ["\"Promoted to VP after applying the frameworks\" — ★★★★★", "\"Launched my dream business in 90 days\" — ★★★★★", "\"Relationship with my kids is transformed\" — ★★★★★", "\"Went from anxious to confident public speaker\" — ★★★★★", "\"Best investment I've ever made in myself\" — ★★★★★", "\"The accountability alone is worth 10x the price\" — ★★★★★"],
    ctaText: "Become a Student",
  },
  {
    id: 50, niche: "Self-Improvement", pageName: "Life Mastery Blueprint", designAngle: DESIGN_ANGLES[9],
    description: "Comprehensive long-form page covering mindset, habits, goals, and transformation.",
    recommendedProducts: ["Complete self-improvement systems", "Premium coaching bundles", "Lifetime access courses", "All-in-one programs"],
    headline: "The Life Mastery Blueprint: Your Complete Transformation System",
    subheadline: "Mindset. Habits. Goals. Relationships. Career. Health. Every dimension of your life, optimized.",
    bodyPoints: ["Morning & evening routine frameworks", "Goal-setting system with built-in accountability", "Habit stacking method for lasting change", "Relationship communication toolkit", "Career advancement strategies", "Stress and emotional regulation techniques", "Monthly live masterclasses with experts", "Lifetime access to all future updates"],
    ctaText: "Get the Full Blueprint",
  },
];
